package com.myspace.p1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class pl implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public pl() {
    }




}